name = "LR_BUG_Sylvester"
uuid = "149d6231-eb5a-4cbf-8ed9-4e2ab481a44a"
version = "1.0.0-DEV"
authors = ["Giorgos Vretinaris"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FStrings = "1e2663ae-5621-49ef-9c0a-672f85872094"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MakiePublication = "dde8697e-0d61-460d-88dd-856f66710dd1"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Accessors = "0.1.42"
CairoMakie = "0.15.6"
Colors = "0.13.1"
FStrings = "0.1.2"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.12.0"
LinearSolve = "3.46.1"
LoopVectorization = "0.12.173"
MakiePublication = "0.4.3"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Revise = "3.11.0"
SparseArrays = "1.12.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
