name = "LR_BUG_Sylvester"
uuid = "149d6231-eb5a-4cbf-8ed9-4e2ab481a44a"
authors = ["Giorgos Vretinaris"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
